# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='posted',
        ),
    ]
